# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'ios-challenge-master' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-challenge-master
	pod 'SnapKit'
	pod 'Moya'
	pod 'Kingfisher'
	plugin 'slather'
	

  target 'ios-challenge-masterTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Nimble-Snapshots'
	pod 'Quick'
	pod 'Nimble'
  end

	target 'ios-challenge-masterUITests' do
inherit! :search_paths
    # Pods for testing
	pod 'Quick'
	pod 'Nimble'
	pod 'KIF'
  end

end
